server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/educator?options=-c%20TimeZone=UTC
    username: educator
    password: educator
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC

  jackson:
    time-zone: UTC
jwt:
  secret: "educator-secret-key-change-later"
  expiration-ms: 3600000

app:
  admin:
    bootstrap:
      email: admin@educator.local
      password: Admin@123
  security:
    cors:
      allowed-origins: http://localhost:3000,http://127.0.0.1:3000
