spring:
  profiles: prod

app:
  admin:
    bootstrap:
      email: ${BOOTSTRAP_ADMIN_EMAIL:}
      password: ${BOOTSTRAP_ADMIN_PASSWORD:}
  security:
    cors:
      allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}
